import type { Job } from '@/components/job-card'

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'シニアフロントエンドエンジニア',
    company: '株式会社テックイノベーション',
    location: '東京都渋谷区（リモート可）',
    salary: '年収 700〜1,000万円',
    tags: ['React', 'TypeScript', 'Next.js'],
    type: '正社員',
    postedAt: '3日前',
    isNew: true,
    isFeatured: true,
    description: 'グローバルに展開するSaaSプロダクトのフロントエンド開発をリードするポジションです。技術的な意思決定から実装まで幅広く担当いただきます。',
  },
  {
    id: '2',
    title: 'プロダクトマネージャー（PM）',
    company: '合同会社ネクストステップ',
    location: '大阪府大阪市',
    salary: '年収 600〜900万円',
    tags: ['プロダクト戦略', 'アジャイル', 'データ分析'],
    type: '正社員',
    postedAt: '1週間前',
    isFeatured: false,
    description: 'BtoB向けクラウドサービスのプロダクトロードマップ策定・実行を担当するPMを募集しています。',
  },
  {
    id: '3',
    title: 'データサイエンティスト',
    company: 'AIテクノロジーズ株式会社',
    location: '東京都千代田区',
    salary: '年収 650〜950万円',
    tags: ['Python', '機械学習', 'SQL', 'BigQuery'],
    type: '正社員',
    postedAt: '2日前',
    isNew: true,
    description: '大規模なユーザーデータを活用した機械学習モデルの開発・運用を担当します。推薦システムの改善プロジェクトを中心に活躍いただきます。',
  },
  {
    id: '4',
    title: 'UX/UIデザイナー',
    company: '株式会社クリエイティブデザイン',
    location: '東京都港区（フルリモート）',
    salary: '年収 500〜750万円',
    tags: ['Figma', 'ユーザーリサーチ', 'プロトタイピング'],
    type: '正社員',
    postedAt: '5日前',
    description: 'スマートフォンアプリのUX設計からUIデザインまで一貫して担当いただきます。ユーザーインタビューや定量分析も重要な業務の一部です。',
  },
  {
    id: '5',
    title: 'バックエンドエンジニア（Go/AWS）',
    company: 'フィンテックソリューションズ株式会社',
    location: '東京都新宿区',
    salary: '年収 650〜900万円',
    tags: ['Go', 'AWS', 'マイクロサービス', 'gRPC'],
    type: '正社員',
    postedAt: '1日前',
    isNew: true,
    isFeatured: true,
    description: '決済インフラの開発・保守を担当するバックエンドエンジニアを募集。高可用性・高スループットのシステム設計経験者を求めています。',
  },
  {
    id: '6',
    title: 'クラウドインフラエンジニア（SRE）',
    company: '株式会社メガスケール',
    location: '東京都品川区（ハイブリッド）',
    salary: '年収 700〜1,100万円',
    tags: ['Kubernetes', 'Terraform', 'AWS', 'SRE'],
    type: '正社員',
    postedAt: '4日前',
    description: 'マルチクラウド環境でのインフラ設計・構築・運用を担当。SREとして信頼性向上に取り組むポジションです。',
  },
  {
    id: '7',
    title: 'Webマーケティングマネージャー',
    company: '株式会社グロースファクター',
    location: '東京都目黒区',
    salary: '年収 550〜800万円',
    tags: ['SEO', 'SEM', 'SNS広告', 'Google Analytics'],
    type: '正社員',
    postedAt: '2週間前',
    description: 'EC事業のデジタルマーケティング戦略の立案・実行を担当。SEO/SEM・SNS広告・メールマーケティングを一手に担います。',
  },
  {
    id: '8',
    title: 'モバイルアプリエンジニア（iOS）',
    company: 'ヘルスケアテック株式会社',
    location: '東京都渋谷区',
    salary: '年収 600〜850万円',
    tags: ['Swift', 'SwiftUI', 'iOS'],
    type: '正社員',
    postedAt: '6日前',
    description: '健康管理アプリのiOSネイティブ開発を担当。SwiftUIを使った最新の開発スタイルで新機能を実装していただきます。',
  },
]

export const mockCompanies = [
  {
    id: 'c1',
    name: '株式会社テックイノベーション',
    industry: 'ITサービス',
    employeeCount: '500〜1,000名',
    location: '東京都渋谷区',
    rating: 4.2,
    reviewCount: 132,
    openJobs: 8,
    tags: ['上場企業', '産休・育休取得率90%以上', 'フレックス制度'],
    description: '国内外10カ国でSaaSプロダクトを展開するグローバルITカンパニー。エンジニアファーストの文化で技術革新を推進しています。',
  },
  {
    id: 'c2',
    name: 'AIテクノロジーズ株式会社',
    industry: 'AI・機械学習',
    employeeCount: '100〜300名',
    location: '東京都千代田区',
    rating: 4.5,
    reviewCount: 87,
    openJobs: 12,
    tags: ['スタートアップ', 'ストックオプション', 'フルリモート'],
    description: '生成AIを活用した業務効率化プラットフォームを開発するスタートアップ。シリーズBで50億円調達済み。',
  },
  {
    id: 'c3',
    name: 'フィンテックソリューションズ株式会社',
    industry: 'フィンテック',
    employeeCount: '300〜500名',
    location: '東京都新宿区',
    rating: 4.0,
    reviewCount: 213,
    openJobs: 5,
    tags: ['上場準備中', '完全週休2日', '社員持株制度'],
    description: '個人・法人向け決済インフラを提供するフィンテック企業。年間取引高1兆円を超える規模のシステムを運営。',
  },
  {
    id: 'c4',
    name: '株式会社クリエイティブデザイン',
    industry: 'デザイン・クリエイティブ',
    employeeCount: '50〜100名',
    location: '東京都港区',
    rating: 4.7,
    reviewCount: 54,
    openJobs: 3,
    tags: ['フルリモート', '副業OK', '成果主義'],
    description: 'エンタープライズ向けのUX/UIデザインコンサルティングファーム。Fortune 500企業との多数のプロジェクト実績あり。',
  },
]
